name: zabbix

services:
  postgres-server:
    image: "${POSTGRESQL_IMAGE}:${POSTGRESQL_IMAGE_TAG}"
    restart: "${RESTART_POLICY}"
    command:
      - postgres
      - -c
      - shared_preload_libraries=timescaledb
      - -c
      - max_connections=200
    env_file:
      - path: ${ENV_VARS_DIRECTORY}/.env_db_pgsql
        required: true
      - path: ${ENV_VARS_DIRECTORY}/.env_db_pgsql_override
        required: false
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ${DATA_DIRECTORY}/var/lib/postgresql/data:/var/lib/postgresql/data:rw
    tmpfs:
      - /tmp
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U "$$(cat /run/secrets/POSTGRES_USER)" -d "$${POSTGRES_DB}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    stop_grace_period: 1m
    networks:
      database:
        aliases:
          - postgres-server

  server-db-init:
    image: "${ZABBIX_SERVER_PGSQL_IMAGE}:${ZBX_IMAGE_TAG}"
    init: true
    attach: true
    read_only: true
    restart: "no"
    command: init_db_only
    env_file:
      - path: ${ENV_VARS_DIRECTORY}/.env_db_pgsql
        required: true
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ${DATA_DIRECTORY}/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
    tmpfs:
      - /tmp
    depends_on:
      postgres-server:
        condition: service_healthy
    networks:
      database:
        aliases:
          - zabbix-server-pgsql-init
    labels:
      com.zabbix.component: "server-db-init"
      com.zabbix.dbtype: "pgsql"

  zabbix-server:
    image: "${ZABBIX_SERVER_PGSQL_IMAGE}:${ZBX_IMAGE_TAG}"
    init: true
    restart: "${RESTART_POLICY}"
    attach: true
    ports:
      - name: zabbix-trapper
        target: 10051
        host_ip: "${ZABBIX_SERVER_BIND_IP}"
        published: "${ZABBIX_SERVER_PORT}"
        protocol: tcp
        app_protocol: zabbix-trapper
    env_file:
      - path: ${ENV_VARS_DIRECTORY}/.env_srv
        required: true
      - path: ${ENV_VARS_DIRECTORY}/.env_srv_override
        required: false
      - path: ${ENV_VARS_DIRECTORY}/.env_db_pgsql
        required: true
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIRECTORY}/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ${DATA_DIRECTORY}/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca:rw
    tmpfs:
      - /tmp
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    depends_on:
      server-db-init:
        condition: service_completed_successfully
      postgres-server:
        condition: service_healthy
    networks:
      database:
      backend:
        aliases:
          - zabbix-server
      frontend:
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.component: "server"
      com.zabbix.dbtype: "pgsql"

  zabbix-web-nginx-pgsql:
    image: "${ZABBIX_WEB_NGINX_PGSQL_IMAGE}:${ZBX_IMAGE_TAG}"
    restart: "${RESTART_POLICY}"
    attach: false
    ports:
      - name: web-http
        target: 8080
        host_ip: "${ZABBIX_WEB_NGINX_BIND_IP}"
        published: "${ZABBIX_WEB_NGINX_HTTP_PORT}"
        protocol: tcp
        app_protocol: http
      - name: web-https
        target: 8443
        host_ip: "${ZABBIX_WEB_NGINX_BIND_IP}"
        published: "${ZABBIX_WEB_NGINX_HTTPS_PORT}"
        protocol: tcp
        app_protocol: https
    env_file:
      - path: ${ENV_VARS_DIRECTORY}/.env_web
        required: true
      - path: ${ENV_VARS_DIRECTORY}/.env_web_override
        required: false
      - path: ${ENV_VARS_DIRECTORY}/.env_db_pgsql
        required: true
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIRECTORY}/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ${DATA_DIRECTORY}/usr/share/zabbix/modules:/usr/share/zabbix/modules:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
    tmpfs:
      - /tmp
      - /var/lib/php/session:mode=770,uid=1997,gid=1995
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 1m30s
      timeout: 3s
      retries: 3
      start_period: 40s
      start_interval: 5s
    depends_on:
      server-db-init:
        condition: service_completed_successfully
      postgres-server:
        condition: service_healthy
      zabbix-server:
        condition: service_started
    networks:
      database:
      backend:
        aliases:
          - zabbix-web-nginx-pgsql
      frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.component: "frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "pgsql"

secrets:
  POSTGRES_USER:
    file: ${ENV_VARS_DIRECTORY}/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ${ENV_VARS_DIRECTORY}/.POSTGRES_PASSWORD

networks:
  frontend:
    name: zabbix_frontend
    enable_ipv6: ${FRONTEND_ENABLE_IPV6}
    ipam:
      config:
        - subnet: ${FRONTEND_SUBNET}

  backend:
    name: zabbix_backend
    enable_ipv6: ${BACKEND_ENABLE_IPV6}
    ipam:
      config:
        - subnet: ${BACKEND_SUBNET}

  database:
    name: zabbix_database
    enable_ipv6: ${DATABASE_NETWORK_ENABLE_IPV6}